
-- Drop existing tables
drop table if exists ikmc_unitrap_mart.unitrap__trapblock_annotation__dm;
drop table if exists ikmc_unitrap_mart.unitrap__trap_unitrap__main;
drop table if exists ikmc_unitrap_mart.unitrap__unitrap__main;
drop table if exists ikmc_unitrap_mart.unitrap__gene__main;

-- Set the storage engine to use
SET storage_engine=MYISAM;

-- MartBuilder SQL (Rebuild the mart)
create table ikmc_unitrap_mart.TEMP0 as select a.region_name as chromosome,a.region_start as gene_start,a.external_name as marker_symbol,a.region_id as region_id_1020_key,a.biotype,a.seq_id as ensembl_gene_id,a.region_strand as strand,a.region_end as gene_end,a.refseq_id from ikmc_unitrapcore.gene as a;
create index I_0 on ikmc_unitrap_mart.TEMP0(gene_start);
create index I_1 on ikmc_unitrap_mart.TEMP0(marker_symbol);
create index I_2 on ikmc_unitrap_mart.TEMP0(gene_end);
create index I_3 on ikmc_unitrap_mart.TEMP0(ensembl_gene_id);
create index I_4 on ikmc_unitrap_mart.TEMP0(refseq_id);
create index I_5 on ikmc_unitrap_mart.TEMP0(chromosome);
create index I_6 on ikmc_unitrap_mart.TEMP0(strand);
rename table ikmc_unitrap_mart.TEMP0 to ikmc_unitrap_mart.unitrap__gene__main;
create index I_7 on ikmc_unitrap_mart.unitrap__gene__main(region_id_1020_key);
create table ikmc_unitrap_mart.TEMP1 as select a.marker_symbol,a.region_id_1020_key,a.strand,a.biotype,a.ensembl_gene_id,a.chromosome,a.gene_end,a.gene_start,a.refseq_id from ikmc_unitrap_mart.unitrap__gene__main as a;
create index I_8 on ikmc_unitrap_mart.TEMP1(region_id_1020_key);
create table ikmc_unitrap_mart.TEMP2 as select a.*,b.hit_db as assembly,b.start as unitrap_start,b.accession as unitrap_accession_id,b.unitrap_id as unitrap_id_1015_key,b.end as unitrap_end,b.ambiguous from ikmc_unitrap_mart.TEMP1 as a left join ikmc_unitrapcore.unitrap as b on a.region_id_1020_key=b.region_id;
drop table ikmc_unitrap_mart.TEMP1;
create index I_9 on ikmc_unitrap_mart.TEMP2(marker_symbol);
create index I_10 on ikmc_unitrap_mart.TEMP2(strand);
create index I_11 on ikmc_unitrap_mart.TEMP2(chromosome);
create index I_12 on ikmc_unitrap_mart.TEMP2(unitrap_end);
create index I_13 on ikmc_unitrap_mart.TEMP2(ensembl_gene_id);
create index I_14 on ikmc_unitrap_mart.TEMP2(unitrap_start);
create index I_15 on ikmc_unitrap_mart.TEMP2(gene_start);
create index I_16 on ikmc_unitrap_mart.TEMP2(gene_end);
create index I_17 on ikmc_unitrap_mart.TEMP2(unitrap_accession_id);
create index I_18 on ikmc_unitrap_mart.TEMP2(refseq_id);
rename table ikmc_unitrap_mart.TEMP2 to ikmc_unitrap_mart.unitrap__unitrap__main;
create index I_19 on ikmc_unitrap_mart.unitrap__unitrap__main(region_id_1020_key);
create index I_20 on ikmc_unitrap_mart.unitrap__unitrap__main(unitrap_id_1015_key);
alter table ikmc_unitrap_mart.unitrap__gene__main add column (unitrap_count integer default 0);
update ikmc_unitrap_mart.unitrap__gene__main a set unitrap_count=(select count(1) from ikmc_unitrap_mart.unitrap__unitrap__main b where a.region_id_1020_key=b.region_id_1020_key and not (b.marker_symbol is null and b.assembly is null and b.ambiguous is null and b.strand is null and b.chromosome is null and b.unitrap_end is null and b.unitrap_id_1015_key is null and b.biotype is null and b.ensembl_gene_id is null and b.unitrap_start is null and b.gene_start is null and b.gene_end is null and b.unitrap_accession_id is null and b.refseq_id is null));
create index I_21 on ikmc_unitrap_mart.unitrap__gene__main(unitrap_count);
alter table ikmc_unitrap_mart.unitrap__unitrap__main add column (unitrap_count integer default 0);
update ikmc_unitrap_mart.unitrap__unitrap__main a set unitrap_count=(select max(unitrap_count) from ikmc_unitrap_mart.unitrap__gene__main b where a.region_id_1020_key=b.region_id_1020_key);
create index I_22 on ikmc_unitrap_mart.unitrap__unitrap__main(unitrap_count);
create table ikmc_unitrap_mart.TEMP3 as select a.marker_symbol,a.unitrap_accession_id,a.region_id_1020_key,a.assembly,a.strand,a.chromosome,a.unitrap_start,a.ambiguous,a.unitrap_count,a.unitrap_end,a.unitrap_id_1015_key,a.biotype,a.ensembl_gene_id,a.gene_end,a.gene_start,a.refseq_id from ikmc_unitrap_mart.unitrap__unitrap__main as a;
create index I_23 on ikmc_unitrap_mart.TEMP3(unitrap_id_1015_key);
create table ikmc_unitrap_mart.TEMP4 as select a.*,b.trap_id as trap_id_1011,b.trapblock_id as trapblock_id_1011,b.trap_unitrap_id as trap_unitrap_id_1011_key from ikmc_unitrap_mart.TEMP3 as a left join ikmc_unitrapcore.trap_unitrap as b on a.unitrap_id_1015_key=b.unitrap_id;
drop table ikmc_unitrap_mart.TEMP3;
create index I_24 on ikmc_unitrap_mart.TEMP4(trap_id_1011);
create table ikmc_unitrap_mart.TEMP5 as select a.*,b.trap_name,b.n_percent_masked,b.x_masked_seq,b.max_frag_length_N_splitted as max_frag_length_n_splitted,b.x_percent_masked,b.gss_id as dbgss_id,b.seq_length_not_N as seq_length_not_n,b.sequencing_direction,b.esclone_id as esclone_id_1010,b.xrepeat,b.nrepeat,b.gb_locus as genbank_accession_id,b.sequence,b.gb_id as genbank_id,b.seq_length,b.mol_type as molecule_type from ikmc_unitrap_mart.TEMP4 as a left join ikmc_unitrapcore.trap as b on a.trap_id_1011=b.trap_id;
drop table ikmc_unitrap_mart.TEMP4;
create index I_25 on ikmc_unitrap_mart.TEMP5(esclone_id_1010);
create table ikmc_unitrap_mart.TEMP6 as select a.*,b.clone as escell_clone,b.vector_name,b.strain as escell_strain,b.project_id as project_id_102,b.design_type,b.cell_line as escell_line,b.vector_type from ikmc_unitrap_mart.TEMP5 as a left join ikmc_unitrapcore.esclone as b on a.esclone_id_1010=b.esclone_id;
drop table ikmc_unitrap_mart.TEMP5;
create index I_26 on ikmc_unitrap_mart.TEMP6(project_id_102);
create table ikmc_unitrap_mart.TEMP7 as select a.*,b.project_name as project,b.url as project_url,b.note as project_notes from ikmc_unitrap_mart.TEMP6 as a left join ikmc_unitrapcore.project as b on a.project_id_102=b.project_id;
drop table ikmc_unitrap_mart.TEMP6;
alter table ikmc_unitrap_mart.TEMP7 drop column project_id_102;
create index I_27 on ikmc_unitrap_mart.TEMP7(escell_clone);
create index I_28 on ikmc_unitrap_mart.TEMP7(strand);
create index I_29 on ikmc_unitrap_mart.TEMP7(chromosome);
create index I_30 on ikmc_unitrap_mart.TEMP7(gene_start);
create index I_31 on ikmc_unitrap_mart.TEMP7(molecule_type);
create index I_32 on ikmc_unitrap_mart.TEMP7(refseq_id);
create index I_33 on ikmc_unitrap_mart.TEMP7(unitrap_accession_id);
create index I_34 on ikmc_unitrap_mart.TEMP7(escell_line);
create index I_35 on ikmc_unitrap_mart.TEMP7(genbank_id);
create index I_36 on ikmc_unitrap_mart.TEMP7(ensembl_gene_id);
create index I_37 on ikmc_unitrap_mart.TEMP7(gene_end);
create index I_38 on ikmc_unitrap_mart.TEMP7(marker_symbol);
create index I_39 on ikmc_unitrap_mart.TEMP7(unitrap_start);
create index I_40 on ikmc_unitrap_mart.TEMP7(project);
create index I_41 on ikmc_unitrap_mart.TEMP7(unitrap_end);
create index I_42 on ikmc_unitrap_mart.TEMP7(design_type);
create index I_43 on ikmc_unitrap_mart.TEMP7(escell_strain);
create index I_44 on ikmc_unitrap_mart.TEMP7(genbank_accession_id);
create index I_45 on ikmc_unitrap_mart.TEMP7(dbgss_id);
rename table ikmc_unitrap_mart.TEMP7 to ikmc_unitrap_mart.unitrap__trap_unitrap__main;
create index I_46 on ikmc_unitrap_mart.unitrap__trap_unitrap__main(unitrap_id_1015_key);
create index I_47 on ikmc_unitrap_mart.unitrap__trap_unitrap__main(trap_unitrap_id_1011_key);
alter table ikmc_unitrap_mart.unitrap__unitrap__main add column (trap_unitrap_count integer default 0);
update ikmc_unitrap_mart.unitrap__unitrap__main a set trap_unitrap_count=(select count(1) from ikmc_unitrap_mart.unitrap__trap_unitrap__main b where a.unitrap_id_1015_key=b.unitrap_id_1015_key and not (b.escell_clone is null and b.trap_id_1011 is null and b.strand is null and b.chromosome is null and b.sequence is null and b.biotype is null and b.vector_type is null and b.gene_start is null and b.molecule_type is null and b.refseq_id is null and b.unitrap_accession_id is null and b.esclone_id_1010 is null and b.seq_length_not_n is null and b.escell_line is null and b.genbank_id is null and b.project_url is null and b.ensembl_gene_id is null and b.x_masked_seq is null and b.gene_end is null and b.marker_symbol is null and b.project_notes is null and b.assembly is null and b.n_percent_masked is null and b.nrepeat is null and b.xrepeat is null and b.unitrap_start is null and b.seq_length is null and b.project is null and b.unitrap_end is null and b.max_frag_length_n_splitted is null and b.trap_name is null and b.trapblock_id_1011 is null and b.design_type is null and b.escell_strain is null and b.region_id_1020_key is null and b.trap_unitrap_id_1011_key is null and b.ambiguous is null and b.x_percent_masked is null and b.vector_name is null and b.sequencing_direction is null and b.genbank_accession_id is null and b.dbgss_id is null));
create index I_48 on ikmc_unitrap_mart.unitrap__unitrap__main(trap_unitrap_count);
alter table ikmc_unitrap_mart.unitrap__trap_unitrap__main add column (trap_unitrap_count integer default 0);
update ikmc_unitrap_mart.unitrap__trap_unitrap__main a set trap_unitrap_count=(select max(trap_unitrap_count) from ikmc_unitrap_mart.unitrap__unitrap__main b where a.unitrap_id_1015_key=b.unitrap_id_1015_key);
create index I_49 on ikmc_unitrap_mart.unitrap__trap_unitrap__main(trap_unitrap_count);
create table ikmc_unitrap_mart.TEMP8 as select a.trap_unitrap_id_1011_key,a.trapblock_id_1011 from ikmc_unitrap_mart.unitrap__trap_unitrap__main as a;
create index I_50 on ikmc_unitrap_mart.TEMP8(trapblock_id_1011);
create table ikmc_unitrap_mart.TEMP9 as select a.*,b.rank as unitrap_rank,b.intronic,b.coverage,b.region_id as region_id_1022,b.flanking_exon_id as flanking_exon_id_1022,b.trapblock_annotation_id as trapblock_annotation_id_1022,b.comment from ikmc_unitrap_mart.TEMP8 as a inner join ikmc_unitrapcore.trapblock_annotation as b on a.trapblock_id_1011=b.trapblock_id;
drop table ikmc_unitrap_mart.TEMP8;
create index I_51 on ikmc_unitrap_mart.TEMP9(flanking_exon_id_1022);
create table ikmc_unitrap_mart.TEMP10 as select a.*,b.region_start as exon_start,b.rank as exon_rank,b.seq_id as ensembl_exon_id,b.region_end as exon_end from ikmc_unitrap_mart.TEMP9 as a inner join ikmc_unitrapcore.region as b on a.flanking_exon_id_1022=b.region_id;
drop table ikmc_unitrap_mart.TEMP9;
create index I_52 on ikmc_unitrap_mart.TEMP10(trap_unitrap_id_1011_key);
create table ikmc_unitrap_mart.TEMP11 as select a.trap_unitrap_id_1011_key,b.exon_rank,b.region_id_1022,b.trapblock_id_1011,b.unitrap_rank,b.trapblock_annotation_id_1022,b.coverage,b.exon_end,b.comment,b.ensembl_exon_id,b.intronic,b.flanking_exon_id_1022,b.exon_start from ikmc_unitrap_mart.unitrap__trap_unitrap__main as a left join ikmc_unitrap_mart.TEMP10 as b on a.trap_unitrap_id_1011_key=b.trap_unitrap_id_1011_key;
drop table ikmc_unitrap_mart.TEMP10;
create index I_53 on ikmc_unitrap_mart.TEMP11(exon_end);
create index I_54 on ikmc_unitrap_mart.TEMP11(ensembl_exon_id);
create index I_55 on ikmc_unitrap_mart.TEMP11(intronic);
create index I_56 on ikmc_unitrap_mart.TEMP11(exon_start);
rename table ikmc_unitrap_mart.TEMP11 to ikmc_unitrap_mart.unitrap__trapblock_annotation__dm;
create index I_57 on ikmc_unitrap_mart.unitrap__trapblock_annotation__dm(trap_unitrap_id_1011_key);
