production:
  apachectl: /usr/sbin/apache2ctl
  port: 8080
  proxy: 80
  host: biomart.helmholtz-muenchen.de
  location: biomart
  logger: "FATAL,Screen"
  databases:
    - name: ikmc_unitrap
      display_name: "IKMC UniTrap"
      host: 
      port: 
      user: 
      password: 
      staging_db: biomart_unitrapcore
      standard: 
        database: biomart_unitrap_mart
      alt:
        database: biomart_unitrap_mart_alt
      
    
  

test:
  apachectl: /software/team87/brave_new_world/app/httpd-2.2.14/bin/apachectl
  port: 3010
  http_proxy: http://wwwcache.sanger.ac.uk:3128
  location: biomart
  logger: "INFO,logFile"
  databases:
    - name: ikmc_unitrap
      display_name: "IKMC UniTrap"
      host: 
      port: 
      user: 
      password: 
      staging_db: ikmc_unitrapcore
      standard: 
        database: ikmc_unitrap_mart
      alt:
        database: ikmc_unitrap_mart_alt
      
    
  

